### ISSUE TITLE
Items on the web menu should be disabled when no song is playing

### ISSUE THREAD

**Issue by asermax** [afrancoto/WebMenu#1]
Not that it really affects functionallity (if you use any of the items of the menu when no song is playing, it just throws an exception in the background), but for the sake of correctness, the menu items should be disabled or somehow let the user know that there needs to be a song playing for the actions to work.

Btw, thanks for the extension :]

**Comment by afrancoto** [comment]
Thanks for the tip! I updated the code, now the menu is hidden when no song is playing!

**Comment by afrancoto** [comment]
https://github.com/afrancoto/WebMenu/issues/4
