### ISSUE TITLE
Review check_service_order() function

### ISSUE THREAD

**Issue by afrancoto** [afrancoto/WebMenu#20]
<pre>
##########
#The "check_services_order" function is called by the "apply_settings" function in WebMenu.py. It eliminates settings errors. 
##########
    def check_services_order(self):
    global services_order, shortcuts
    changed=False #The services order and shortcuts are rewritten only if one of them is changed by this function

    services_order_changed=services_order
    for service, data in services.items():
        if service not in services_order: 
            services_order_changed.append(service) #If a service is missing from the "service-order" key, it is added at the end
            changed=True
    for service in services_order:
        if service not in services: 
            services_order_changed.remove(service) #If a service is missing from the "services" key, it is also deleted from the "service-order" key
            changed=True

    shortcuts_changed=shortcuts
    for service in shortcuts: 
        if service not in services: 
            del shortcuts_changed[service] #If a service is missing from the "services" key, it is also deleted from the "shortcuts" key
            changed=True

    if changed: 
        self.settings['services-order']=services_order_changed
        self.settings['shortcuts']=shortcuts_changed
</pre>

I got this error when a service in `shortcuts` is not in `services`:

<pre>
Traceback (most recent call last):
  File "/home/andrea/.local/share/rhythmbox/plugins/WebMenu/WebMenu.py", line 309, in do_activate
    self.apply_settings('oldsettings', 'all' , shell, config) #Calls "apply_settings"
  File "/home/andrea/.local/share/rhythmbox/plugins/WebMenu/WebMenu.py", line 252, in apply_settings
    config.check_services_order() #Checks settings integrity
  File "/home/andrea/.local/share/rhythmbox/plugins/WebMenu/WebMenu_config.py", line 64, in check_services_order
    for service in shortcuts: 
RuntimeError: dictionary changed size during iteration
</pre>

**Comment by asermax** [comment]
Here `shortcuts_changed=shortcuts`, you are asigning a reference of the same object pointed by `shortcuts` to `shortucts_changed`, so when you iterate `shortcuts`, you are iterating the same dict as `shortcut_changed`. If you delete a key:value pair from `shortcuts_changed`, you are also deleting it from `shortcuts` and violating the iterator contract.
You should change `shortcuts_changed=shortcuts` for `shortcuts_changed=dict(shortcuts)`

Lol, this inline code format is fun :F

**Comment by afrancoto** [comment]
Thanks! Now works!
I can't find any other bug, if it's ok for you tonight I will merge testing and master, WebMenu 2.0 will be out! :D

**Comment by asermax** [comment]
I think there's one or two bugs going around there, but yeah, i think it's stable enough d: 
Gonna see if I can find something else by tonight
