### ISSUE TITLE
warning messages on startup

### ISSUE THREAD

**Issue by fossfreedom** [afrancoto/WebMenu#3]
launching rhythmbox 2.97 from a terminal I see the following warning messages... anything to worry about?

<pre>
dad@dad-VirtualBox:~/.local/share/rhythmbox/plugins/WebMenu$ rhythmbox

(rhythmbox:3044): Gtk-WARNING **: Refusing to add non-unique action 'search_on_youtube_action' to action group 'WebMenuActionGroup'

(rhythmbox:3044): Gtk-WARNING **: Refusing to add non-unique action 'album_wikipedia' to action group 'WebMenuActionGroup'

(rhythmbox:3044): Gtk-WARNING **: Refusing to add non-unique action 'artist_allmusic' to action group 'WebMenuActionGroup'

(rhythmbox:3044): Gtk-WARNING **: Refusing to add non-unique action 'artist_torrentz' to action group 'WebMenuActionGroup'
</pre>

**Comment by afrancoto** [comment]
I get the same warnings, I don't know why they show up! :P I googled the problem without success, I'll try again as soon as possible, now i'm writing the next version with the option window :D

**Comment by asermax** [comment]
The warnings come up 'coz you are registering those actions twice in the draw_menu method. It doesn't cause any problems tho.

Anyway, deleting the extras 'add_action' after the 'add_action_with_accel' will get ride of those warnings :3

**Comment by afrancoto** [comment]
Thank you! I fix it right now! :D
