### ISSUE TITLE
makefile does not install plugin

### ISSUE THREAD

**Issue by fossfreedom** [afrancoto/WebMenu#7]
the makefile does not install correctly - you run sudo make and it doesnt install to the use local directory - only to the root user.

perhaps instead of a make file you could just use an `install.sh`

example

<pre>
# install schema
sudo cp ./org.gnome.rhythmbox.plugins.llyrics.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

# install plugin
mkdir -p ~/.local/share/rhythmbox/plugins/
rm -r -f ~/.local/share/rhythmbox/plugins/WebMenu/
cp -r * ~/.local/share/rhythmbox/plugins/WebMenu
</pre>

**Comment by afrancoto** [comment]
<pre>
PLUGIN_PATH=~/.local/share/rhythmbox/plugins/WebMenu
install: upschema
    @echo Installing Rhythmbox Web Menu:
    @rm -Rf $(PLUGIN_PATH)
    @mkdir -p $(PLUGIN_PATH)
    @cp * $(PLUGIN_PATH) -Rf
    @echo DONE!
uninstall:
    @echo Removing Rhythmbox Web Menu:
    @rm -Rf $(PLUGIN_PATH) /usr/share/glib-2.0/schemas/org.gnome.rhythmbox.plugins.webmenu.gschema.xml
    @glib-compile-schemas /usr/share/glib-2.0/schemas
    @echo DONE!
upschema:
    @cp org.gnome.rhythmbox.plugins.webmenu.gschema.xml /usr/share/glib-2.0/schemas 
    @glib-compile-schemas /usr/share/glib-2.0/schemas
</pre>


`sudo make install` installs the plugin in ~/.local/share/rhythmbox/plugins/WebMenu if you are running it as you your user and not as root (it works for me). 
The commands are pretty much the same, am I wrong?

**Comment by fossfreedom** [comment]
similar yes - although didnt work for me ... probably because I had just cloned directly into `./local/share/rhythmbox/plugins/`

I've been looking at many plugins from other authors - many of them use the `sh install.sh` method - probably a good idea to follow the "crowd" - it makes it easier for people to install your plugin if they see a similar installation method.

Anyway - your choice - its just a suggestion.

Hope this helps.

**Comment by afrancoto** [comment]
Ok, tomorrow I will add the install.sh file! :D

**Comment by afrancoto** [comment]
Install.sh added in the testing branch!
It's based on the one written by asermax for `lastfm_extension`, with an uninstall option and some more output...

Just one more bug to  fix and WebMenu 2.0 will be ready!! :D

**Comment by fossfreedom** [comment]
hey - superb stuff.  Well done!

So - what's your next project? :D

**Comment by afrancoto** [comment]
Thanks :)
No idea, I will have to study for the msc, so it all depends on how much free time I will have! :S
