### ISSUE TITLE
Change the name of the 'config' module

### ISSUE THREAD

**Issue by asermax** [afrancoto/WebMenu#9]
I would like to say this is just a 'wishlist' issue, but I think it affects functionality in some ways.
I propose this change since using a generic name for your config module can (and will) conflict with other plugins that have the same naming policy. 
To be clearer, wenever a plugin is loaded into Rhythmbox, all the modules of the plugins are imported to the global namespace of the plugin system. So, if two plugins have a module with the same name, only the plugin that gets activated first will have it's module loaded into memory. When the second plugin imports the module, it won't load it's own, but use the one already on memory, causing the second plugin to fail.

I came around this bug while using the ReplayGain plugin concurrently with yours, after the latests updates. This other plugin also names it's configuration module as 'config', causing the conflict I explained above.

**Comment by afrancoto** [comment]
Thanks for the hint! I moved config.py to WebMenu_config.py and changed the imports in WebMenu.py :D
